import type { Metadata } from "next"
import "./globals.css"
import AuthContext from "@/utils/AuthContext"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="kr">
			<body>
				<AuthContext>
					<main className="min-h-screen flex flex-col">{children}</main>
				</AuthContext>
			</body>
		</html>
	)
}
