import type { Metadata } from "next"
import "./globals.css"
import AuthContext from "@/utils/AuthContext"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/react"

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="kr">
			<body>
				<SpeedInsights />
				<Analytics />
				<AuthContext>
					<main className="min-h-screen flex flex-col">{children}</main>
				</AuthContext>
			</body>
		</html>
	)
}
